/* 
 * $Id: TimeStampAdapter.java,v 1.0 2013-01-23 23:10:07 averab Exp $
 *
 * @copyright Universidad Carlos III de Madrid. proprietary/confidential. Use is subject to license terms.
 */
package es.uc3m.softlab.cbi4api.gbas.event.subscriber.xsd;

import java.util.Calendar;
import javax.xml.bind.annotation.adapters.XmlAdapter;

/**
 * This file was pre-generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation and later
 * self-modified to meet the F4BPA specs.
 *   
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 *  
 * @author averab
 * @version 1.0.0
 */
public class TimeStampAdapter extends XmlAdapter<String, Calendar> {
	/**
	 * Convert a value type to a bound type. 
	 * @param value value to convert.
	 */
    public Calendar unmarshal(String value) {
        return (javax.xml.bind.DatatypeConverter.parseDateTime(value));
    }
    /**
     * Convert a bound type to a value type. 
     * @param value bound type to convert.
     */
    public String marshal(Calendar value) {
        if (value == null) {
            return null;
        }
        return (javax.xml.bind.DatatypeConverter.printDateTime(value));
    }
}
