//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.19 at 11:16:16 PM IST 
//


package es.uc3m.softlab.cbi4api.gbas.event.subscriber.xsd.basu.event;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ActivityParent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivityParent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActivityDefinitionID" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *         &lt;element name="ActivityInstanceID" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivityParent", propOrder = {
    "activityDefinitionID",
    "activityInstanceID"
})
public class ActivityParent
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ActivityDefinitionID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String activityDefinitionID;
    @XmlElement(name = "ActivityInstanceID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String activityInstanceID;

    /**
     * Gets the value of the activityDefinitionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityDefinitionID() {
        return activityDefinitionID;
    }

    /**
     * Sets the value of the activityDefinitionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityDefinitionID(String value) {
        this.activityDefinitionID = value;
    }

    public boolean isSetActivityDefinitionID() {
        return (this.activityDefinitionID!= null);
    }

    /**
     * Gets the value of the activityInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityInstanceID() {
        return activityInstanceID;
    }

    /**
     * Sets the value of the activityInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityInstanceID(String value) {
        this.activityInstanceID = value;
    }

    public boolean isSetActivityInstanceID() {
        return (this.activityInstanceID!= null);
    }

}
