//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.12 at 10:15:14 PM IST 
//


package es.uc3m.softlab.cbi4api.gbas.event.subscriber.xsd.basu.event;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Correlation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Correlation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessInstanceID" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="CorrelationData" type="{http://www.uc3m.es/softlab/basu/event}CorrelationData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Correlation", propOrder = {
    "processInstanceID",
    "correlationData"
})
public class Correlation
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ProcessInstanceID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String processInstanceID;
    @XmlElement(name = "CorrelationData")
    protected CorrelationData correlationData;

    /**
     * Gets the value of the processInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessInstanceID() {
        return processInstanceID;
    }

    /**
     * Sets the value of the processInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessInstanceID(String value) {
        this.processInstanceID = value;
    }

    public boolean isSetProcessInstanceID() {
        return (this.processInstanceID!= null);
    }

    /**
     * Gets the value of the correlationData property.
     * 
     * @return
     *     possible object is
     *     {@link CorrelationData }
     *     
     */
    public CorrelationData getCorrelationData() {
        return correlationData;
    }

    /**
     * Sets the value of the correlationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrelationData }
     *     
     */
    public void setCorrelationData(CorrelationData value) {
        this.correlationData = value;
    }

    public boolean isSetCorrelationData() {
        return (this.correlationData!= null);
    }

}
